create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,avatar_url text,created_at timestamptz default now());
create table if not exists public.chats(id uuid primary key default gen_random_uuid(),name text,is_group boolean default false,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.chat_members(chat_id uuid references public.chats(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text default 'member',joined_at timestamptz default now(),primary key(chat_id,user_id));
create table if not exists public.messages(id uuid primary key default gen_random_uuid(),chat_id uuid not null references public.chats(id) on delete cascade,sender_id uuid not null references auth.users(id) on delete cascade,content text,file_url text,file_name text,edited_at timestamptz,created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.chats enable row level security; alter table public.chat_members enable row level security; alter table public.messages enable row level security;
create policy "profiles read" on public.profiles for select to authenticated using(true);
create policy "profiles own update" on public.profiles for update to authenticated using(auth.uid()=id);
create policy "profiles own insert" on public.profiles for insert to authenticated with check(auth.uid()=id);
create policy "members read own chats" on public.chat_members for select to authenticated using(user_id=auth.uid());
create policy "members insert own" on public.chat_members for insert to authenticated with check(user_id=auth.uid());
create policy "chats select member" on public.chats for select to authenticated using(exists(select 1 from public.chat_members m where m.chat_id=id and m.user_id=auth.uid()));
create policy "chats create" on public.chats for insert to authenticated with check(created_by is null or created_by=auth.uid());
create policy "messages read member" on public.messages for select to authenticated using(exists(select 1 from public.chat_members m where m.chat_id=messages.chat_id and m.user_id=auth.uid()));
create policy "messages send member" on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.chat_members m where m.chat_id=messages.chat_id and m.user_id=auth.uid()));
create policy "messages update own" on public.messages for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid());
create policy "messages delete own" on public.messages for delete to authenticated using(sender_id=auth.uid());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))) on conflict(id) do nothing; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.find_private_chat(other_user uuid) returns table(chat_id uuid) language sql security definer set search_path=public as $$select c.id from chats c where not c.is_group and exists(select 1 from chat_members a where a.chat_id=c.id and a.user_id=auth.uid()) and exists(select 1 from chat_members b where b.chat_id=c.id and b.user_id=other_user) limit 1;$$;
grant execute on function public.find_private_chat(uuid) to authenticated;
alter publication supabase_realtime add table public.messages;
insert into storage.buckets(id,name,public) values('avatars','avatars',true) on conflict(id) do nothing;
insert into storage.buckets(id,name,public) values('chat-files','chat-files',true) on conflict(id) do nothing;
create policy "avatar read" on storage.objects for select to authenticated using(bucket_id='avatars');
create policy "avatar upload own" on storage.objects for insert to authenticated with check(bucket_id='avatars' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "file read" on storage.objects for select to authenticated using(bucket_id='chat-files');
create policy "file upload own" on storage.objects for insert to authenticated with check(bucket_id='chat-files' and auth.uid()::text=(storage.foldername(name))[1]);