-- EMCHAT PRO V5: safe schema/migration for an existing project
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique, display_name text not null default 'Пользователь', avatar_url text, bio text, last_seen timestamptz default now(), created_at timestamptz default now());
create table if not exists public.chats (id uuid primary key default gen_random_uuid(), kind text not null check(kind in ('dm','group','channel')), title text, description text, avatar_url text, invite_code text unique, owner_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz default now());
create table if not exists public.chat_members (chat_id uuid not null references public.chats(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'member' check(role in ('owner','admin','member')),permissions jsonb not null default '{}'::jsonb,muted_until timestamptz,joined_at timestamptz default now(),primary key(chat_id,user_id));
create table if not exists public.messages (id uuid primary key default gen_random_uuid(),chat_id uuid not null references public.chats(id) on delete cascade,sender_id uuid not null references auth.users(id) on delete cascade,content text not null default '',attachment_url text,attachment_name text,attachment_type text,created_at timestamptz default now(),edited_at timestamptz);
alter table public.messages add column if not exists attachment_url text; alter table public.messages add column if not exists attachment_name text; alter table public.messages add column if not exists attachment_type text; alter table public.messages add column if not exists edited_at timestamptz;
create table if not exists public.chat_bans (id uuid primary key default gen_random_uuid(),chat_id uuid not null references public.chats(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,banned_by uuid references auth.users(id) on delete set null,reason text,created_at timestamptz default now(),unique(chat_id,user_id));
create table if not exists public.pinned_messages (chat_id uuid primary key references public.chats(id) on delete cascade,message_id uuid references public.messages(id) on delete cascade,pinned_by uuid references auth.users(id),pinned_at timestamptz default now());
create table if not exists public.devices (id text primary key,user_id uuid not null references auth.users(id) on delete cascade,name text,user_agent text,last_seen timestamptz default now(),created_at timestamptz default now());
create index if not exists messages_chat_created_idx on public.messages(chat_id,created_at); create index if not exists members_user_idx on public.chat_members(user_id); create index if not exists bans_chat_user_idx on public.chat_bans(chat_id,user_id);
-- helpers
create or replace function public.is_chat_member(p_chat_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from chat_members where chat_id=p_chat_id and user_id=p_user_id)$$;
create or replace function public.has_chat_permission(p_chat_id uuid,p_permission text,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from chat_members m where m.chat_id=p_chat_id and m.user_id=p_user_id and (m.role='owner' or (m.role='admin' and coalesce((m.permissions->>p_permission)::boolean,false))))$$;
create or replace function public.ban_chat_member(p_chat_id uuid,p_user_id uuid) returns void language plpgsql security definer set search_path=public as $$begin if not public.has_chat_permission(p_chat_id,'ban') then raise exception 'No permission'; end if; insert into chat_bans(chat_id,user_id,banned_by) values(p_chat_id,p_user_id,auth.uid()) on conflict(chat_id,user_id) do nothing; delete from chat_members where chat_id=p_chat_id and user_id=p_user_id; end$$;
create or replace function public.transfer_chat_owner(p_chat_id uuid,p_new_owner uuid) returns void language plpgsql security definer set search_path=public as $$declare old_owner uuid; begin select owner_id into old_owner from chats where id=p_chat_id; if old_owner is distinct from auth.uid() then raise exception 'Only owner can transfer'; end if; if not exists(select 1 from chat_members where chat_id=p_chat_id and user_id=p_new_owner) then raise exception 'New owner must be member'; end if; update chats set owner_id=p_new_owner where id=p_chat_id; update chat_members set role='admin' where chat_id=p_chat_id and user_id=old_owner; update chat_members set role='owner' where chat_id=p_chat_id and user_id=p_new_owner; end$$;
create or replace function public.find_dm(other_user uuid) returns public.chats language sql security definer set search_path=public as $$select c.* from chats c where c.kind='dm' and exists(select 1 from chat_members a where a.chat_id=c.id and a.user_id=auth.uid()) and exists(select 1 from chat_members b where b.chat_id=c.id and b.user_id=other_user) limit 1$$;
-- RLS
alter table public.profiles enable row level security; alter table public.chats enable row level security; alter table public.chat_members enable row level security; alter table public.messages enable row level security; alter table public.chat_bans enable row level security; alter table public.pinned_messages enable row level security; alter table public.devices enable row level security;
drop policy if exists "profiles read" on public.profiles; create policy "profiles read" on public.profiles for select to authenticated using(true); drop policy if exists "profiles own" on public.profiles; create policy "profiles own" on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists "chats member read" on public.chats; create policy "chats member read" on public.chats for select to authenticated using(public.is_chat_member(id)); drop policy if exists "chats create" on public.chats; create policy "chats create" on public.chats for insert to authenticated with check(owner_id=auth.uid()); drop policy if exists "chats edit" on public.chats; create policy "chats edit" on public.chats for update to authenticated using(public.has_chat_permission(id,'edit_chat'));
drop policy if exists "members read" on public.chat_members; create policy "members read" on public.chat_members for select to authenticated using(public.is_chat_member(chat_id)); drop policy if exists "members join" on public.chat_members; create policy "members join" on public.chat_members for insert to authenticated with check(user_id=auth.uid() and not exists(select 1 from chat_bans b where b.chat_id=chat_id and b.user_id=auth.uid())); drop policy if exists "members leave" on public.chat_members; create policy "members leave" on public.chat_members for delete to authenticated using(user_id=auth.uid() or public.has_chat_permission(chat_id,'kick'));
drop policy if exists "messages read" on public.messages; create policy "messages read" on public.messages for select to authenticated using(public.is_chat_member(chat_id)); drop policy if exists "messages send" on public.messages; create policy "messages send" on public.messages for insert to authenticated with check(sender_id=auth.uid() and public.is_chat_member(chat_id) and not exists(select 1 from chat_members m where m.chat_id=chat_id and m.user_id=auth.uid() and m.muted_until>now()) and not exists(select 1 from chats c where c.id=chat_id and c.kind='channel' and not public.has_chat_permission(chat_id,'send_messages'))); drop policy if exists "messages own edit" on public.messages; create policy "messages own edit" on public.messages for update to authenticated using(sender_id=auth.uid()); drop policy if exists "messages own delete" on public.messages; create policy "messages own delete" on public.messages for delete to authenticated using(sender_id=auth.uid() or public.has_chat_permission(chat_id,'pin'));
drop policy if exists "bans read" on public.chat_bans; create policy "bans read" on public.chat_bans for select to authenticated using(public.is_chat_member(chat_id)); drop policy if exists "bans manage" on public.chat_bans; create policy "bans manage" on public.chat_bans for all to authenticated using(public.has_chat_permission(chat_id,'ban')) with check(public.has_chat_permission(chat_id,'ban'));
drop policy if exists "devices own" on public.devices; create policy "devices own" on public.devices for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant execute on function public.ban_chat_member(uuid,uuid) to authenticated; grant execute on function public.transfer_chat_owner(uuid,uuid) to authenticated; grant execute on function public.find_dm(uuid) to authenticated;
-- Realtime
do $$ begin alter publication supabase_realtime add table public.messages; exception when duplicate_object then null; end $$;
