'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {upload} from '@vercel/blob/client';
import {supabase} from '@/lib/supabase';
import {Search,Send,Paperclip,Plus,MoreVertical,Settings,Users,LogOut,Edit3,Trash2,UserPlus,Shield,VolumeX,UserX,Ban,Pin,PinOff,Image as ImageIcon,Video,FileText,X,ChevronLeft,UserRound,Link as LinkIcon,Copy,Check,Camera,Save,Crown,ShieldCheck,Smartphone,LogOut as KickIcon,Reply,Menu} from 'lucide-react';

type Kind='dm'|'group'|'channel';
type Chat={id:string;kind:Kind;title:string|null;description:string|null;avatar_url:string|null;invite_code:string|null;owner_id:string;created_at?:string};
type Profile={id:string;display_name:string;username:string|null;avatar_url:string|null;bio?:string|null};
type Member={chat_id:string;user_id:string;role:'owner'|'admin'|'member';permissions:Record<string,boolean>;muted_until:string|null;joined_at:string;profile?:Profile};
type Message={id:string;chat_id:string;sender_id:string;content:string;attachment_url:string|null;attachment_name:string|null;attachment_type:string|null;created_at:string;edited_at:string|null;reply_to_id:string|null;profile?:Profile};
type Tab='chat'|'members'|'bans'|'devices'|'profile'|'pinned';
type Device={id:string;user_id:string;name?:string|null;device_name?:string|null;device_type?:string|null;user_agent?:string|null;last_seen?:string|null;last_seen_at?:string|null;created_at?:string|null;is_current?:boolean|null};
const PERMS=['send_messages','invite','pin','kick','ban','unban','mute','edit_chat'] as const;
const fullPerm=Object.fromEntries(PERMS.map(x=>[x,true]));

export default function ChatApp(){
 const [me,setMe]=useState<any>(null); const [myProfile,setMyProfile]=useState<Profile|null>(null); const [chats,setChats]=useState<Chat[]>([]); const [active,setActive]=useState<Chat|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [members,setMembers]=useState<Member[]>([]); const [text,setText]=useState(''); const [file,setFile]=useState<File|null>(null); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [modal,setModal]=useState<'create'|'info'|'editChat'|null>(null); const [tab,setTab]=useState<Tab>('chat'); const [editing,setEditing]=useState<Message|null>(null); const [reply,setReply]=useState<Message|null>(null); const [deviceId,setDeviceId]=useState(''); const [pinned,setPinned]=useState<Message|null>(null); const [bans,setBans]=useState<(Profile&{reason?:string|null;user_id:string})[]>([]); const [devices,setDevices]=useState<Device[]>([]); const [devicesError,setDevicesError]=useState(''); const [busy,setBusy]=useState(false); const [mobile,setMobile]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const avatarRef=useRef<HTMLInputElement>(null);
 const myMember=members.find(m=>m.user_id===me?.id); const can=(p:string)=>active?.owner_id===me?.id||myMember?.role==='owner'||(myMember?.role==='admin'&&!!myMember.permissions?.[p]);
 useEffect(()=>{let id=localStorage.getItem('emchat-device-id');if(!id){id=crypto.randomUUID();localStorage.setItem('emchat-device-id',id)}setDeviceId(id);void boot();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'&&!session?.user){location.replace('/auth')}});const heartbeat=window.setInterval(()=>void heartbeatDevice(),15000);const onVisible=()=>{if(document.visibilityState==='visible')void heartbeatDevice()};document.addEventListener('visibilitychange',onVisible);return()=>{subscription.unsubscribe();window.clearInterval(heartbeat);document.removeEventListener('visibilitychange',onVisible)}},[]);
 useEffect(()=>{if(!active||!me)return; void loadMessages();void loadMembers();void loadPinned();const ch=supabase.channel('emchat-'+active.id).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`chat_id=eq.${active.id}`},()=>void loadMessages()).on('postgres_changes',{event:'*',schema:'public',table:'chat_members',filter:`chat_id=eq.${active.id}`},()=>void loadMembers()).subscribe();return()=>{supabase.removeChannel(ch)}},[active?.id,me?.id]);
 async function boot(){try{const {data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user){location.replace('/auth');return}setMe(user);const fallback=user.user_metadata?.display_name||user.email?.split('@')[0]||'Пользователь';const now=new Date().toISOString();const {error:profileError}=await supabase.from('profiles').upsert({id:user.id,display_name:fallback,last_seen:now},{onConflict:'id'});if(profileError)console.warn('Profile bootstrap:',profileError.message);const {data:p,error:profileLoadError}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(profileLoadError)console.warn('Profile load:',profileLoadError.message);setMyProfile(p as Profile|null);let id=localStorage.getItem('emchat-device-id');if(!id){id=crypto.randomUUID();localStorage.setItem('emchat-device-id',id)}setDeviceId(id);await registerDevice(user.id,id);await loadChats();await loadDevicesFor(user.id);setLoading(false)}catch(error){console.error('EMCHAT boot error',error);setLoading(false)}}
 async function registerDevice(userId:string,id:string){const ua=navigator.userAgent;const type=/Mobi|Android|iPhone|iPad/i.test(ua)?'mobile':'desktop';const name=type==='mobile'?'Телефон':'Компьютер';const now=new Date().toISOString();const {error}=await supabase.from('devices').upsert({id,user_id:userId,name,device_type:type,user_agent:ua,last_seen:now,is_current:true},{onConflict:'id'});if(error){console.error('Device register:',error.message);setDevicesError(`Не удалось сохранить устройство: ${error.message}`);sessionStorage.removeItem('emchat-device-registered');return false}sessionStorage.setItem('emchat-device-registered','1');setDevicesError('');return true}
 async function heartbeatDevice(){const id=localStorage.getItem('emchat-device-id');const user=me||((await supabase.auth.getUser()).data.user);if(!id||!user?.id)return;const {data,error}=await supabase.from('devices').select('id').eq('id',id).eq('user_id',user.id).maybeSingle();if(error){console.warn('Device heartbeat:',error.message);return}if(!data){/* Не выходим из аккаунта из-за временной ошибки/миграции БД. */ if(sessionStorage.getItem('emchat-device-registered')==='1'){await supabase.auth.signOut();location.replace('/auth')} return}const {error:updateError}=await supabase.from('devices').update({last_seen:new Date().toISOString(),is_current:true}).eq('id',id).eq('user_id',user.id);if(updateError)console.warn('Device heartbeat update:',updateError.message)}
 async function loadChats(){const {data,error}=await supabase.rpc('get_my_chats');if(error){console.error(error);return}const list=(data||[]) as Chat[];setChats(list);const wanted=new URLSearchParams(location.search).get('chat');const pick=list.find(c=>c.id===wanted)||active&&list.find(c=>c.id===active.id)||list[0]||null;setActive(pick as Chat|null)}
 async function loadMessages(){if(!active)return;const {data,error}=await supabase.from('messages').select('*').eq('chat_id',active.id).order('created_at');if(error)return;const rows=(data||[]) as Message[];const ids=[...new Set(rows.map(x=>x.sender_id))];let ps:Profile[]=[];if(ids.length){const r=await supabase.from('profiles').select('id,display_name,username,avatar_url,bio').in('id',ids);ps=(r.data||[]) as Profile[]}const map=new Map(ps.map(p=>[p.id,p]));setMessages(rows.map(m=>({...m,profile:map.get(m.sender_id)})))}
 async function loadMembers(){if(!active)return;const {data}=await supabase.from('chat_members').select('*').eq('chat_id',active.id).order('joined_at');const rows=(data||[]) as Member[];const ids=rows.map(x=>x.user_id);let ps:Profile[]=[];if(ids.length){const r=await supabase.from('profiles').select('id,display_name,username,avatar_url,bio').in('id',ids);ps=(r.data||[]) as Profile[]}const map=new Map(ps.map(p=>[p.id,p]));setMembers(rows.map(m=>({...m,profile:map.get(m.user_id)})))}
 async function loadPinned(){if(!active)return;const {data}=await supabase.from('pinned_messages').select('message_id,messages(*)').eq('chat_id',active.id).maybeSingle();setPinned((data as any)?.messages||null)}
 async function loadBans(){if(!active)return;const {data,error}=await supabase.rpc('get_chat_bans',{p_chat_id:active.id});if(error){alert(error.message);return}setBans(data||[])}
 async function loadDevicesFor(userId:string){let rows:any[]=[];const {data,error}=await supabase.rpc('get_my_devices');if(!error){rows=(data||[]) as any[]}else{const fallback=await supabase.from('devices').select('*').eq('user_id',userId);if(fallback.error){console.error('Devices load:',fallback.error.message);setDevicesError(fallback.error.message);setDevices([]);return}rows=(fallback.data||[]) as any[]}rows.sort((a,b)=>{const ac=a.id===deviceId?1:0,bc=b.id===deviceId?1:0;if(ac!==bc)return bc-ac;const at=new Date(a.last_seen||a.last_seen_at||a.created_at||0).getTime(),bt=new Date(b.last_seen||b.last_seen_at||b.created_at||0).getTime();return bt-at});setDevices(rows as Device[]);setDevicesError('')}
 async function loadDevices(){if(!me?.id)return;await loadDevicesFor(me.id)}
 async function openInfo(t:Tab='chat'){setTab(t);setModal('info');if(t==='bans')await loadBans();if(t==='devices')await loadDevices();}
 async function send(){if(!active||!me||(!text.trim()&&!file)||busy)return;setBusy(true);try{if(editing){const {error}=await supabase.from('messages').update({content:text.trim(),edited_at:new Date().toISOString()}).eq('id',editing.id);if(error)throw error;setEditing(null)}else{let attachment:any={};if(file){if(file.size>50*1024*1024)throw new Error('Максимальный размер файла — 50 МБ');const blob=await upload(`emchat/${me.id}/${Date.now()}-${file.name}`,file,{access:'public',handleUploadUrl:'/api/upload'});attachment={attachment_url:blob.url,attachment_name:file.name,attachment_type:file.type||'application/octet-stream'}}const {error}=await supabase.from('messages').insert({chat_id:active.id,sender_id:me.id,content:text.trim(),reply_to_id:reply?.id||null,...attachment});if(error)throw error}setText('');setFile(null);setReply(null);await loadMessages()}catch(e){alert(e instanceof Error?e.message:'Не удалось отправить')}finally{setBusy(false)}}
 async function createChat(kind:Kind,title:string,description:string,username:string){if(kind==='dm'){const {data,error}=await supabase.rpc('create_direct_chat',{p_username:username.replace('@','')});if(error)throw error;await loadChats();const {data:c}=await supabase.from('chats').select('*').eq('id',data).single();if(c)setActive(c as Chat);setModal(null);return}const {data,error}=await supabase.rpc('create_chat_v7',{p_kind:kind,p_title:title,p_description:description});if(error)throw error;await loadChats();const {data:c}=await supabase.from('chats').select('*').eq('id',data).single();if(c)setActive(c as Chat);setModal(null)}
 async function deleteMessage(m:Message){if(!confirm('Удалить сообщение?'))return;const {error}=await supabase.from('messages').delete().eq('id',m.id);if(error)alert(error.message)}
 async function pinMessage(m:Message){if(!active)return;const {error}=await supabase.rpc('pin_chat_message',{p_chat_id:active.id,p_message_id:m.id});if(error)alert(error.message);else await loadPinned()}
 async function unpin(){if(!active)return;const {error}=await supabase.rpc('unpin_chat_message',{p_chat_id:active.id});if(error)alert(error.message);else setPinned(null)}
 async function updateMember(m:Member,action:'kick'|'ban'|'mute'|'admin'|'member'|'permissions'){if(!active)return;try{if(action==='kick'){if(!confirm('Исключить пользователя?'))return;await rpc('kick_chat_member',{p_chat_id:active.id,p_user_id:m.user_id})}else if(action==='ban'){if(!confirm('Забанить пользователя?'))return;await rpc('ban_chat_member',{p_chat_id:active.id,p_user_id:m.user_id,p_reason:null})}else if(action==='mute'){const minutes=Number(prompt('Мут на сколько минут?', '60'));if(!Number.isFinite(minutes)||minutes<=0)return;await rpc('mute_chat_member',{p_chat_id:active.id,p_user_id:m.user_id,p_minutes:minutes})}else if(action==='admin'||action==='member'){await rpc('set_chat_member_role',{p_chat_id:active.id,p_user_id:m.user_id,p_role:action,p_permissions:action==='admin'?fullPerm:{}})}else{const next={...m.permissions};PERMS.forEach(p=>{next[p]=confirm(`Разрешение «${p}» для ${m.profile?.display_name||'админа'}? OK = разрешить, Отмена = запретить`) });await rpc('set_chat_member_role',{p_chat_id:active.id,p_user_id:m.user_id,p_role:'admin',p_permissions:next})}await loadMembers()}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}}
 async function rpc(fn:string,args:Record<string,unknown>){const {error}=await supabase.rpc(fn,args);if(error)throw error}
 async function unban(userId:string){if(!active)return;try{await rpc('unban_chat_member',{p_chat_id:active.id,p_user_id:userId});await loadBans()}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}}
 async function transfer(userId:string){if(!active||!confirm('Передать владельца? Это действие изменит права владельца.'))return;try{await rpc('transfer_chat_owner',{p_chat_id:active.id,p_new_owner:userId});await loadChats();await loadMembers()}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}}
 async function saveChat(title:string,description:string,avatar?:File|null){if(!active)return;try{let avatar_url=active.avatar_url;if(avatar){if(avatar.size>50*1024*1024)throw new Error('Максимум 50 МБ');const blob=await upload(`emchat/chat/${active.id}/${Date.now()}-${avatar.name}`,avatar,{access:'public',handleUploadUrl:'/api/upload'});avatar_url=blob.url}const {error}=await supabase.from('chats').update({title,description,avatar_url}).eq('id',active.id);if(error)throw error;setActive({...active,title,description,avatar_url});await loadChats();setModal(null)}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}}
 async function saveProfile(display_name:string,username:string,bio:string,avatar?:File|null){try{let avatar_url=myProfile?.avatar_url||null;if(avatar){if(avatar.size>50*1024*1024)throw new Error('Максимальный размер аватарки — 50 МБ');const blob=await upload(`emchat/avatar/${me.id}/${Date.now()}-${avatar.name}`,avatar,{access:'public',handleUploadUrl:'/api/upload'});avatar_url=blob.url}const {data,error}=await supabase.from('profiles').update({display_name,username:username.replace('@','')||null,bio,avatar_url}).eq('id',me.id).select().single();if(error)throw error;setMyProfile(data as Profile)}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}}
 async function inviteMember(){if(!active)return;const u=prompt('Username пользователя, например: @ivan');if(!u)return;try{await rpc('add_member_by_username',{p_chat_id:active.id,p_username:u.replace('@','')});await loadMembers()}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}}
 async function copyInvite(){if(!active?.invite_code)return;await navigator.clipboard.writeText(`${location.origin}/join/${active.invite_code}`);alert('Ссылка скопирована')}
 async function kickDevice(id:string){if(id===deviceId){alert('Текущее устройство нельзя кикнуть отсюда. Используйте «Выйти из аккаунта».');return}if(!confirm('Кикнуть устройство? На нём сессия EMCHAT будет завершена при следующей проверке (обычно до 15 секунд).'))return;setBusy(true);try{const {error}=await supabase.rpc('kick_my_device',{p_device_id:id});if(error){const fallback=await supabase.from('devices').delete().eq('id',id).eq('user_id',me.id);if(fallback.error)throw fallback.error}await loadDevices()}catch(e){alert((e as any)?.message||'Не удалось кикнуть устройство')}finally{setBusy(false)}}
 async function logout(){await supabase.auth.signOut();location.href='/auth'}
 const filtered=useMemo(()=>chats.filter(c=>(c.title||'').toLowerCase().includes(query.toLowerCase())||c.description?.toLowerCase().includes(query.toLowerCase())),[chats,query]);
 if(loading)return <div className="loading">Загрузка EMCHAT…</div>;
 return <main className="appShell"><aside className={'sidebar '+(mobile?'mobileOpen':'')}><div className="sidebarTop"><div className="brand"><span>E</span><b>EMCHAT</b></div><button className="iconBtn" title="Создать" onClick={()=>setModal('create')}><Plus/></button></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск чатов"/></div><div className="chatList">{filtered.map(c=><button key={c.id} className={'chatRow '+(active?.id===c.id?'active':'')} onClick={()=>{setActive(c);setMobile(false)}}><Avatar src={c.avatar_url} text={c.title||'D'}/><div className="chatMeta"><b>{c.title||'Диалог'}</b><span>{c.kind==='channel'?'Канал':c.kind==='group'?'Группа':'Личные сообщения'}</span></div></button>)}{!filtered.length&&<div className="emptyList">Нет чатов</div>}</div><button className="profileMini" onClick={()=>openInfo('profile')}><Avatar src={myProfile?.avatar_url||null} text={myProfile?.display_name||'E'}/><div><b>{myProfile?.display_name||'Пользователь'}</b><span>@{myProfile?.username||'без_username'}</span></div><MoreVertical size={18}/></button></aside>
 <section className="conversation">{active?<><header className="chatHeader"><button className="iconBtn mobileOnly" onClick={()=>setMobile(true)}><Menu/></button><Avatar src={active.avatar_url} text={active.title||'C'}/><button className="headerTitle" onClick={()=>openInfo('chat')}><b>{active.title||'Диалог'}</b><span>{active.kind==='channel'?'Канал':`${members.length} участников`}</span></button><div className="headerActions">{pinned&&<button className="iconBtn" title="Закреплённое" onClick={()=>openInfo('pinned')}><Pin size={19}/></button>}<button className="iconBtn" onClick={()=>openInfo('chat')}><Settings/></button></div></header>{pinned&&<button className="pinnedBar" onClick={()=>openInfo('pinned')}><Pin size={15}/><span>{pinned.content||pinned.attachment_name||'Медиа'}</span></button>}<div className="messages">{messages.map(m=><MessageCard key={m.id} m={m} mine={m.sender_id===me.id} canPin={can('pin')} onReply={()=>setReply(m)} onEdit={()=>{setEditing(m);setText(m.content)}} onDelete={()=>void deleteMessage(m)} onPin={()=>void pinMessage(m)}/>)}</div>{(editing||reply||file)&&<div className="composerState">{editing?'Редактирование сообщения':reply?`Ответ: ${reply.content||reply.attachment_name||'медиа'}`:file?.name}<button onClick={()=>{setEditing(null);setReply(null);setFile(null)}}><X size={16}/></button></div>}<div className="composer"><input ref={fileRef} hidden type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="iconBtn" onClick={()=>fileRef.current?.click()}><Paperclip/></button><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} placeholder={file?file.name:editing?'Измените сообщение…':'Напишите сообщение…'}/><button className="sendBtn" disabled={busy} onClick={()=>void send()}><Send size={19}/></button></div></>:<div className="empty"><div><b>EMCHAT</b><p>Создай чат или выбери существующий</p><button className="primary" onClick={()=>setModal('create')}>Создать чат</button></div></div>}</section>
 {modal==='create'&&<CreateModal onClose={()=>setModal(null)} onCreate={createChat}/>} {modal==='editChat'&&active&&<EditChatModal chat={active} onClose={()=>setModal(null)} onSave={saveChat}/>} {modal==='info'&&<InfoPanel tab={tab} setTab={async t=>{setTab(t);if(t==='bans')await loadBans();if(t==='devices')await loadDevices()}} me={me} profile={myProfile} active={active} members={members} bans={bans} devices={devices} devicesError={devicesError} deviceId={deviceId} can={can} pinned={pinned} onClose={()=>setModal(null)} onInvite={inviteMember} onCopy={copyInvite} onEditChat={()=>setModal('editChat')} onMemberAction={updateMember} onTransfer={transfer} onUnban={unban} onUnpin={unpin} onSaveProfile={saveProfile} onKickDevice={kickDevice} onLogout={logout}/>}</main>
}
function Avatar({src,text}:{src:string|null|undefined;text:string}){return <div className="avatar">{src?<img src={src} alt=""/>:<span>{text?.trim()?.[0]?.toUpperCase()||'E'}</span>}</div>}
function Attachment({m}:{m:Message}){if(m.attachment_type?.startsWith('image/'))return <img className="media" src={m.attachment_url||''} alt={m.attachment_name||''}/>;if(m.attachment_type?.startsWith('video/'))return <video className="media" controls src={m.attachment_url||''}/>;return <a className="attachment" href={m.attachment_url||'#'} target="_blank"><FileText size={20}/><span>{m.attachment_name||'Файл'}</span></a>}
function MessageCard({m,mine,canPin,onReply,onEdit,onDelete,onPin}:{m:Message;mine:boolean;canPin:boolean;onReply:()=>void;onEdit:()=>void;onDelete:()=>void;onPin:()=>void}){return <div className={'messageWrap '+(mine?'mine':'')}><div className="bubble"><div className="sender">{m.profile?.display_name||'Пользователь'}</div>{m.content&&<div className="messageText">{m.content}</div>}{m.attachment_url&&<Attachment m={m}/>}<div className="messageFoot"><small>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{m.edited_at?' · изм.':''}</small><div className="msgActions"><button title="Ответить" onClick={onReply}><Reply size={14}/></button>{canPin&&<button title="Закрепить" onClick={onPin}><Pin size={14}/></button>}{mine&&<><button onClick={onEdit}><Edit3 size={14}/></button><button onClick={onDelete}><Trash2 size={14}/></button></>}</div></div></div></div>}
function CreateModal({onClose,onCreate}:{onClose:()=>void;onCreate:(k:Kind,t:string,d:string,u:string)=>Promise<void>}){const [kind,setKind]=useState<Kind>('group');const [title,setTitle]=useState('');const [desc,setDesc]=useState('');const [username,setUsername]=useState('');const [busy,setBusy]=useState(false);return <Modal title="Создать" onClose={onClose}><div className="kindTabs">{(['dm','group','channel'] as Kind[]).map(k=><button key={k} className={kind===k?'selected':''} onClick={()=>setKind(k)}>{k==='dm'?'ЛС':k==='group'?'Группа':'Канал'}</button>)}</div>{kind==='dm'?<input placeholder="Username пользователя" value={username} onChange={e=>setUsername(e.target.value)}/>:<><input placeholder="Название" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Описание" value={desc} onChange={e=>setDesc(e.target.value)}/></>}<button className="primary wide" disabled={busy} onClick={async()=>{setBusy(true);try{await onCreate(kind,title,desc,username)}catch(e){alert((e as any)?.message||String(e)||'Ошибка')}finally{setBusy(false)}}}>{busy?'Создание…':'Создать'}</button></Modal>}
function EditChatModal({chat,onClose,onSave}:{chat:Chat;onClose:()=>void;onSave:(t:string,d:string,a?:File|null)=>Promise<void>}){const [title,setTitle]=useState(chat.title||'');const [desc,setDesc]=useState(chat.description||'');const [file,setFile]=useState<File|null>(null);return <Modal title="Настройки чата" onClose={onClose}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Название"/><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Описание"/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary wide" onClick={()=>void onSave(title,desc,file)}>Сохранить</button></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modalBackdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e=>e.stopPropagation()}><header><b>{title}</b><button className="iconBtn" onClick={onClose}><X/></button></header><div className="modalBody">{children}</div></section></div>}
function InfoPanel(props:{tab:Tab;setTab:(t:Tab)=>void;me:any;profile:Profile|null;active:Chat|null;members:Member[];bans:any[];devices:Device[];devicesError:string;deviceId:string;can:(p:string)=>boolean;pinned:Message|null;onClose:()=>void;onInvite:()=>void;onCopy:()=>void;onEditChat:()=>void;onMemberAction:(m:Member,a:any)=>Promise<void>;onTransfer:(id:string)=>Promise<void>;onUnban:(id:string)=>Promise<void>;onUnpin:()=>Promise<void>;onSaveProfile:(n:string,u:string,b:string,a?:File|null)=>Promise<void>;onKickDevice:(id:string)=>Promise<void>;onLogout:()=>Promise<void>}){const {tab,setTab,active}=props;const [editingProfile,setEditingProfile]=useState(false);const [n,setN]=useState(props.profile?.display_name||'');const [u,setU]=useState(props.profile?.username||'');const [bio,setBio]=useState(props.profile?.bio||'');const [avatar,setAvatar]=useState<File|null>(null);if(tab==='profile')return <aside className="infoPanel"><PanelHeader title="Профиль" onClose={props.onClose}/><div className="panelBody">{!editingProfile?<><div className="profileHero"><Avatar src={props.profile?.avatar_url||null} text={props.profile?.display_name||'E'}/><h2>{props.profile?.display_name}</h2><span>@{props.profile?.username||'без_username'}</span><p>{props.profile?.bio||'Нет описания'}</p></div><button className="primary wide" onClick={()=>setEditingProfile(true)}><Edit3 size={17}/> Редактировать профиль</button><button className="settingsRow" onClick={()=>setTab('devices')}><Smartphone/>Устройства</button><button className="logout" onClick={()=>void props.onLogout()}><LogOut/>Выйти из аккаунта</button></>:<><input value={n} onChange={e=>setN(e.target.value)} placeholder="Имя"/><input value={u} onChange={e=>setU(e.target.value)} placeholder="Username"/><textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="О себе"/><input type="file" accept="image/*" onChange={e=>setAvatar(e.target.files?.[0]||null)}/><button className="primary wide" onClick={async()=>{await props.onSaveProfile(n,u,bio,avatar);setEditingProfile(false)}}><Save size={17}/>Сохранить</button></>}</div></aside>;
if(tab==='devices')return <aside className="infoPanel"><PanelHeader title="Устройства" onClose={props.onClose}/><div className="panelBody"><button className="backLink" onClick={()=>setTab('profile')}><ChevronLeft size={16}/>Профиль</button><p className="muted">Здесь отображаются активные устройства. При кике устройство будет автоматически выведено из EMCHAT (обычно до 15 секунд).</p>{props.devicesError&&<div className="formError">{props.devicesError}</div>}{props.devices.map(d=>{const current=d.id===props.deviceId||!!d.is_current&&d.id===props.deviceId;const seen=d.last_seen||d.last_seen_at||d.created_at;return <div className="member" key={d.id}><div className="deviceIcon"><Smartphone size={20}/></div><div className="grow"><b>{d.name||d.device_name||'Устройство'} {current?'· это устройство':''}</b><span>{d.device_type==='mobile'?'Мобильное устройство':d.device_type==='desktop'?'Компьютер':d.user_agent||'Неизвестное устройство'}</span><small>{seen?`Активно: ${new Date(seen).toLocaleString()}`:'Время активности неизвестно'}</small></div>{!current&&<button className="smallBtn danger" onClick={()=>void props.onKickDevice(d.id)}>Кикнуть</button>}</div>})}{!props.devices.length&&!props.devicesError&&<p className="muted">Устройства пока не найдены. Обновите страницу — текущее устройство будет зарегистрировано автоматически.</p>}</div></aside>;
return <aside className="infoPanel"><PanelHeader title={active?.title||'Чат'} onClose={props.onClose}/><div className="panelTabs"><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}>Инфо</button><button className={tab==='members'?'active':''} onClick={()=>setTab('members')}>Люди</button><button className={tab==='pinned'?'active':''} onClick={()=>setTab('pinned')}>Закреп</button>{props.can('ban')&&<button className={tab==='bans'?'active':''} onClick={()=>setTab('bans')}>Баны</button>}</div><div className="panelBody">{tab==='chat'&&<><div className="profileHero"><Avatar src={active?.avatar_url||null} text={active?.title||'C'}/><h2>{active?.title}</h2><span>{active?.kind==='channel'?'Канал':active?.kind==='group'?'Группа':'Личные сообщения'}</span><p>{active?.description||'Нет описания'}</p></div>{active?.kind!=='dm'&&<><button className="settingsRow" onClick={props.onCopy}><LinkIcon/>Скопировать ссылку-приглашение</button>{props.can('invite')&&<button className="settingsRow" onClick={props.onInvite}><UserPlus/>Добавить участника</button>}{props.can('edit_chat')&&<button className="settingsRow" onClick={props.onEditChat}><Edit3/>Название, описание и аватар</button>}</>}</>}{tab==='members'&&<>{props.members.map(m=><MemberRow key={m.user_id} m={m} me={props.me} owner={active?.owner_id===props.me.id} can={props.can} onAction={props.onMemberAction} onTransfer={props.onTransfer}/>)}</>}{tab==='bans'&&<>{props.bans.map(b=><div className="member" key={b.user_id}><Avatar src={b.avatar_url} text={b.display_name}/><div className="grow"><b>{b.display_name}</b><span>@{b.username||'без_username'}</span><small>{b.reason||'Без причины'}</small></div><button className="smallBtn" onClick={()=>void props.onUnban(b.user_id)}>Разбанить</button></div>)}{!props.bans.length&&<p className="muted">Список забаненных пуст</p>}</>}{tab==='pinned'&&<>{props.pinned?<div className="pinnedCard"><Pin/><b>{props.pinned.profile?.display_name||'Сообщение'}</b><p>{props.pinned.content||props.pinned.attachment_name||'Медиа'}</p>{props.can('pin')&&<button className="smallBtn" onClick={()=>void props.onUnpin()}><PinOff size={15}/>Открепить</button>}</div>:<p className="muted">Нет закреплённых сообщений</p>}</>}</div></aside>}
function PanelHeader({title,onClose}:{title:string;onClose:()=>void}){return <header className="panelHeader"><b>{title}</b><button className="iconBtn" onClick={onClose}><X/></button></header>}
function MemberRow({m,me,owner,can,onAction,onTransfer}:{m:Member;me:any;owner:boolean;can:(p:string)=>boolean;onAction:(m:Member,a:any)=>Promise<void>;onTransfer:(id:string)=>Promise<void>}){const self=m.user_id===me.id;return <div className="member"><Avatar src={m.profile?.avatar_url||null} text={m.profile?.display_name||'U'}/><div className="grow"><b>{m.profile?.display_name||'Пользователь'} {m.role==='owner'&&<Crown size={14} className="inlineIcon"/>}{m.role==='admin'&&<ShieldCheck size={14} className="inlineIcon"/>}</b><span>@{m.profile?.username||'без_username'}</span>{m.muted_until&&new Date(m.muted_until)>new Date()&&<small>Мут до {new Date(m.muted_until).toLocaleString()}</small>}</div>{!self&&<details className="memberMenu"><summary><MoreVertical size={18}/></summary><div>{can('kick')&&<button onClick={()=>void onAction(m,'kick')}><UserX/>Кикнуть</button>}{can('ban')&&<button onClick={()=>void onAction(m,'ban')}><Ban/>Забанить</button>}{can('mute')&&<button onClick={()=>void onAction(m,'mute')}><VolumeX/>Мут</button>}{owner&&m.role!=='owner'&&<button onClick={()=>void onTransfer(m.user_id)}><Crown/>Передать владельца</button>}{can('edit_chat')&&m.role==='member'&&<button onClick={()=>void onAction(m,'admin')}><Shield/>Сделать админом</button>}{can('edit_chat')&&m.role==='admin'&&<><button onClick={()=>void onAction(m,'permissions')}><ShieldCheck/>Права админа</button><button onClick={()=>void onAction(m,'member')}><UserRound/>Снять админа</button></>}</div></details>}</div>}
